// Mocks generated by Mockito 5.4.5 from annotations
// in concordia_nav/test/indoor_map/indoor_routing_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:concordia_nav/data/repositories/calendar.dart' as _i7;
import 'package:device_calendar/device_calendar.dart' as _i3;
import 'package:geolocator_platform_interface/src/enums/enums.dart' as _i6;
import 'package:geolocator_platform_interface/src/geolocator_platform_interface.dart'
    as _i4;
import 'package:geolocator_platform_interface/src/models/models.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePosition_0 extends _i1.SmartFake implements _i2.Position {
  _FakePosition_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeviceCalendarPlugin_1 extends _i1.SmartFake
    implements _i3.DeviceCalendarPlugin {
  _FakeDeviceCalendarPlugin_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GeolocatorPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeolocatorPlatform extends _i1.Mock
    implements _i4.GeolocatorPlatform {
  MockGeolocatorPlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.LocationPermission> checkPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermission, []),
            returnValue: _i5.Future<_i6.LocationPermission>.value(
              _i6.LocationPermission.denied,
            ),
          )
          as _i5.Future<_i6.LocationPermission>);

  @override
  _i5.Future<_i6.LocationPermission> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i5.Future<_i6.LocationPermission>.value(
              _i6.LocationPermission.denied,
            ),
          )
          as _i5.Future<_i6.LocationPermission>);

  @override
  _i5.Future<bool> isLocationServiceEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationServiceEnabled, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i2.Position?> getLastKnownPosition({
    bool? forceLocationManager = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLastKnownPosition, [], {
              #forceLocationManager: forceLocationManager,
            }),
            returnValue: _i5.Future<_i2.Position?>.value(),
          )
          as _i5.Future<_i2.Position?>);

  @override
  _i5.Future<_i2.Position> getCurrentPosition({
    _i2.LocationSettings? locationSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, [], {
              #locationSettings: locationSettings,
            }),
            returnValue: _i5.Future<_i2.Position>.value(
              _FakePosition_0(
                this,
                Invocation.method(#getCurrentPosition, [], {
                  #locationSettings: locationSettings,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Position>);

  @override
  _i5.Stream<_i6.ServiceStatus> getServiceStatusStream() =>
      (super.noSuchMethod(
            Invocation.method(#getServiceStatusStream, []),
            returnValue: _i5.Stream<_i6.ServiceStatus>.empty(),
          )
          as _i5.Stream<_i6.ServiceStatus>);

  @override
  _i5.Stream<_i2.Position> getPositionStream({
    _i2.LocationSettings? locationSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPositionStream, [], {
              #locationSettings: locationSettings,
            }),
            returnValue: _i5.Stream<_i2.Position>.empty(),
          )
          as _i5.Stream<_i2.Position>);

  @override
  _i5.Future<_i6.LocationAccuracyStatus> requestTemporaryFullAccuracy({
    required String? purposeKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestTemporaryFullAccuracy, [], {
              #purposeKey: purposeKey,
            }),
            returnValue: _i5.Future<_i6.LocationAccuracyStatus>.value(
              _i6.LocationAccuracyStatus.reduced,
            ),
          )
          as _i5.Future<_i6.LocationAccuracyStatus>);

  @override
  _i5.Future<_i6.LocationAccuracyStatus> getLocationAccuracy() =>
      (super.noSuchMethod(
            Invocation.method(#getLocationAccuracy, []),
            returnValue: _i5.Future<_i6.LocationAccuracyStatus>.value(
              _i6.LocationAccuracyStatus.reduced,
            ),
          )
          as _i5.Future<_i6.LocationAccuracyStatus>);

  @override
  _i5.Future<bool> openAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openAppSettings, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> openLocationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openLocationSettings, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  double distanceBetween(
    double? startLatitude,
    double? startLongitude,
    double? endLatitude,
    double? endLongitude,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#distanceBetween, [
              startLatitude,
              startLongitude,
              endLatitude,
              endLongitude,
            ]),
            returnValue: 0.0,
          )
          as double);

  @override
  double bearingBetween(
    double? startLatitude,
    double? startLongitude,
    double? endLatitude,
    double? endLongitude,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#bearingBetween, [
              startLatitude,
              startLongitude,
              endLatitude,
              endLongitude,
            ]),
            returnValue: 0.0,
          )
          as double);
}

/// A class which mocks [CalendarRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarRepository extends _i1.Mock
    implements _i7.CalendarRepository {
  MockCalendarRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.DeviceCalendarPlugin get plugin =>
      (super.noSuchMethod(
            Invocation.getter(#plugin),
            returnValue: _FakeDeviceCalendarPlugin_1(
              this,
              Invocation.getter(#plugin),
            ),
          )
          as _i3.DeviceCalendarPlugin);

  @override
  set plugin(_i3.DeviceCalendarPlugin? _plugin) => super.noSuchMethod(
    Invocation.setter(#plugin, _plugin),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> checkPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermissions, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i7.UserCalendar>> getUserCalendars() =>
      (super.noSuchMethod(
            Invocation.method(#getUserCalendars, []),
            returnValue: _i5.Future<List<_i7.UserCalendar>>.value(
              <_i7.UserCalendar>[],
            ),
          )
          as _i5.Future<List<_i7.UserCalendar>>);

  @override
  _i5.Future<List<_i7.UserCalendarEvent>> getEvents(
    List<_i7.UserCalendar>? selectedCalendars,
    Duration? timeSpan,
    DateTime? utcStart,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEvents, [
              selectedCalendars,
              timeSpan,
              utcStart,
            ]),
            returnValue: _i5.Future<List<_i7.UserCalendarEvent>>.value(
              <_i7.UserCalendarEvent>[],
            ),
          )
          as _i5.Future<List<_i7.UserCalendarEvent>>);

  @override
  _i5.Future<List<_i7.UserCalendarEvent>> getEventsOnLocalDate(
    List<_i7.UserCalendar>? selectedCalendars,
    int? offset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEventsOnLocalDate, [
              selectedCalendars,
              offset,
            ]),
            returnValue: _i5.Future<List<_i7.UserCalendarEvent>>.value(
              <_i7.UserCalendarEvent>[],
            ),
          )
          as _i5.Future<List<_i7.UserCalendarEvent>>);
}
