// Mocks generated by Mockito 5.4.5 from annotations
// in concordia_nav/test/directions/outdoor_directions_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:concordia_nav/data/services/outdoor_directions_service.dart'
    as _i4;
import 'package:google_directions_api/google_directions_api.dart' as _i2;
import 'package:google_maps_flutter/google_maps_flutter.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDirectionsService_0 extends _i1.SmartFake
    implements _i2.DirectionsService {
  _FakeDirectionsService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DirectionsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDirectionsService extends _i1.Mock implements _i2.DirectionsService {
  MockDirectionsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> route(
    _i2.DirectionsRequest? request,
    void Function(_i2.DirectionsResult, _i2.DirectionsStatus?)? callback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#route, [request, callback]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ODSDirectionsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockODSDirectionsService extends _i1.Mock
    implements _i4.ODSDirectionsService {
  MockODSDirectionsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DirectionsService get directionsService =>
      (super.noSuchMethod(
            Invocation.getter(#directionsService),
            returnValue: _FakeDirectionsService_0(
              this,
              Invocation.getter(#directionsService),
            ),
          )
          as _i2.DirectionsService);

  @override
  set directionsService(_i2.DirectionsService? _directionsService) =>
      super.noSuchMethod(
        Invocation.setter(#directionsService, _directionsService),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<List<_i5.LatLng>> fetchRoute(
    String? originAddress,
    String? destinationAddress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRoute, [originAddress, destinationAddress]),
            returnValue: _i3.Future<List<_i5.LatLng>>.value(<_i5.LatLng>[]),
          )
          as _i3.Future<List<_i5.LatLng>>);

  @override
  _i3.Future<List<_i5.LatLng>> fetchRouteFromCoords(
    _i5.LatLng? origin,
    String? destinationAddress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRouteFromCoords, [
              origin,
              destinationAddress,
            ]),
            returnValue: _i3.Future<List<_i5.LatLng>>.value(<_i5.LatLng>[]),
          )
          as _i3.Future<List<_i5.LatLng>>);
}
