coverage:
  status:
    project: # More options at https://docs.codecov.com/docs/commit-status
      default:
        target: auto
        threshold: 0%
        base: auto
        informational: true
    patch:
      default:
        informational: true
