name: Create .env File
description: Generates .env file using secrets
inputs:
  google-maps-api-key:
    description: 'Google Maps API key'
    required: true
runs:
  using: "composite"
  steps:
    - name: Create .env file
      shell: bash
      run: |
        touch .env
        echo "GOOGLE_MAPS_API_KEY=${{ inputs.google-maps-api-key }}" >> .env