// Mocks generated by Mockito 5.4.5 from annotations
// in concordia_nav/test/calendar/calendar_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i12;

import 'package:calendar_view/calendar_view.dart' as _i10;
import 'package:concordia_nav/data/domain-model/concordia_room.dart' as _i6;
import 'package:concordia_nav/data/repositories/calendar.dart' as _i4;
import 'package:concordia_nav/utils/building_viewmodel.dart' as _i7;
import 'package:concordia_nav/utils/calendar_selection_viewmodel.dart' as _i8;
import 'package:concordia_nav/utils/calendar_viewmodel.dart' as _i9;
import 'package:device_calendar/device_calendar.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:shared_preferences/shared_preferences.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDeviceCalendarPlugin_0 extends _i1.SmartFake
    implements _i2.DeviceCalendarPlugin {
  _FakeDeviceCalendarPlugin_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferencesAsync_1 extends _i1.SmartFake
    implements _i3.SharedPreferencesAsync {
  _FakeSharedPreferencesAsync_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CalendarRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarRepository extends _i1.Mock
    implements _i4.CalendarRepository {
  MockCalendarRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DeviceCalendarPlugin get plugin =>
      (super.noSuchMethod(
            Invocation.getter(#plugin),
            returnValue: _FakeDeviceCalendarPlugin_0(
              this,
              Invocation.getter(#plugin),
            ),
          )
          as _i2.DeviceCalendarPlugin);

  @override
  set plugin(_i2.DeviceCalendarPlugin? _plugin) => super.noSuchMethod(
    Invocation.setter(#plugin, _plugin),
    returnValueForMissingStub: null,
  );

  @override
  _i3.SharedPreferencesAsync get prefs =>
      (super.noSuchMethod(
            Invocation.getter(#prefs),
            returnValue: _FakeSharedPreferencesAsync_1(
              this,
              Invocation.getter(#prefs),
            ),
          )
          as _i3.SharedPreferencesAsync);

  @override
  set prefs(_i3.SharedPreferencesAsync? _prefs) => super.noSuchMethod(
    Invocation.setter(#prefs, _prefs),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> checkPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermissions, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i4.UserCalendar>> getUserCalendars({
    dynamic preferredCalendarsOnly = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserCalendars, [], {
              #preferredCalendarsOnly: preferredCalendarsOnly,
            }),
            returnValue: _i5.Future<List<_i4.UserCalendar>>.value(
              <_i4.UserCalendar>[],
            ),
          )
          as _i5.Future<List<_i4.UserCalendar>>);

  @override
  _i5.Future<bool> isCalendarPreferred(_i4.UserCalendar? cal) =>
      (super.noSuchMethod(
            Invocation.method(#isCalendarPreferred, [cal]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setUserCalendarPreferredState(_i4.UserCalendar? cal) =>
      (super.noSuchMethod(
            Invocation.method(#setUserCalendarPreferredState, [cal]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i4.UserCalendarEvent>> getEvents(
    List<_i4.UserCalendar>? selectedCalendars,
    Duration? timeSpan,
    DateTime? utcStart,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEvents, [
              selectedCalendars,
              timeSpan,
              utcStart,
            ]),
            returnValue: _i5.Future<List<_i4.UserCalendarEvent>>.value(
              <_i4.UserCalendarEvent>[],
            ),
          )
          as _i5.Future<List<_i4.UserCalendarEvent>>);

  @override
  _i5.Future<List<_i4.UserCalendarEvent>> getEventsOnLocalDate(
    List<_i4.UserCalendar>? selectedCalendars,
    int? offset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEventsOnLocalDate, [
              selectedCalendars,
              offset,
            ]),
            returnValue: _i5.Future<List<_i4.UserCalendarEvent>>.value(
              <_i4.UserCalendarEvent>[],
            ),
          )
          as _i5.Future<List<_i4.UserCalendarEvent>>);

  @override
  _i5.Future<_i4.UserCalendarEvent?> getNextClassEvent(
    List<_i4.UserCalendar>? selectedCalendars,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNextClassEvent, [selectedCalendars]),
            returnValue: _i5.Future<_i4.UserCalendarEvent?>.value(),
          )
          as _i5.Future<_i4.UserCalendarEvent?>);

  @override
  _i5.Future<_i6.ConcordiaRoom?> getNextClassRoom(
    List<_i4.UserCalendar>? selectedCalendars,
    _i7.BuildingViewModel? buildingViewModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNextClassRoom, [
              selectedCalendars,
              buildingViewModel,
            ]),
            returnValue: _i5.Future<_i6.ConcordiaRoom?>.value(),
          )
          as _i5.Future<_i6.ConcordiaRoom?>);
}

/// A class which mocks [CalendarSelectionViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarSelectionViewModel extends _i1.Mock
    implements _i8.CalendarSelectionViewModel {
  MockCalendarSelectionViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set calendarRepository(_i4.CalendarRepository? repo) => super.noSuchMethod(
    Invocation.setter(#calendarRepository, repo),
    returnValueForMissingStub: null,
  );

  @override
  List<_i4.UserCalendar> get calendars =>
      (super.noSuchMethod(
            Invocation.getter(#calendars),
            returnValue: <_i4.UserCalendar>[],
          )
          as List<_i4.UserCalendar>);

  @override
  _i5.Future<void> loadCalendars() =>
      (super.noSuchMethod(
            Invocation.method(#loadCalendars, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isCalendarSelected(_i4.UserCalendar? calendar) =>
      (super.noSuchMethod(
            Invocation.method(#isCalendarSelected, [calendar]),
            returnValue: false,
          )
          as bool);

  @override
  void selectCalendar(_i4.UserCalendar? calendar) => super.noSuchMethod(
    Invocation.method(#selectCalendar, [calendar]),
    returnValueForMissingStub: null,
  );

  @override
  void unselectCalendar(_i4.UserCalendar? calendar) => super.noSuchMethod(
    Invocation.method(#unselectCalendar, [calendar]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleCalendarSelection(_i4.UserCalendar? calendar) =>
      super.noSuchMethod(
        Invocation.method(#toggleCalendarSelection, [calendar]),
        returnValueForMissingStub: null,
      );

  @override
  List<_i4.UserCalendar> getSelectedCalendars() =>
      (super.noSuchMethod(
            Invocation.method(#getSelectedCalendars, []),
            returnValue: <_i4.UserCalendar>[],
          )
          as List<_i4.UserCalendar>);

  @override
  void selectCalendarsByDisplayName(String? displayName) => super.noSuchMethod(
    Invocation.method(#selectCalendarsByDisplayName, [displayName]),
    returnValueForMissingStub: null,
  );

  @override
  List<_i4.UserCalendar> getSelectedCalendarsByDisplayName(
    String? displayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSelectedCalendarsByDisplayName, [
              displayName,
            ]),
            returnValue: <_i4.UserCalendar>[],
          )
          as List<_i4.UserCalendar>);
}

/// A class which mocks [CalendarViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarViewModel extends _i1.Mock implements _i9.CalendarViewModel {
  MockCalendarViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.UserCalendar> get allCalendars =>
      (super.noSuchMethod(
            Invocation.getter(#allCalendars),
            returnValue: <_i4.UserCalendar>[],
          )
          as List<_i4.UserCalendar>);

  @override
  List<_i4.UserCalendar> get selectedCalendars =>
      (super.noSuchMethod(
            Invocation.getter(#selectedCalendars),
            returnValue: <_i4.UserCalendar>[],
          )
          as List<_i4.UserCalendar>);

  @override
  List<_i4.UserCalendarEvent> get events =>
      (super.noSuchMethod(
            Invocation.getter(#events),
            returnValue: <_i4.UserCalendarEvent>[],
          )
          as List<_i4.UserCalendarEvent>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  set calendarRepository(_i4.CalendarRepository? repo) => super.noSuchMethod(
    Invocation.setter(#calendarRepository, repo),
    returnValueForMissingStub: null,
  );

  @override
  set eventsList(List<_i4.UserCalendarEvent>? events) => super.noSuchMethod(
    Invocation.setter(#eventsList, events),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> initialize({_i4.UserCalendar? selectedCalendar}) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #selectedCalendar: selectedCalendar,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  List<_i10.CalendarEventData<Object?>> getCalendarEventData() =>
      (super.noSuchMethod(
            Invocation.method(#getCalendarEventData, []),
            returnValue: <_i10.CalendarEventData<Object?>>[],
          )
          as List<_i10.CalendarEventData<Object?>>);

  @override
  String formatEventTime(_i4.UserCalendarEvent? event) =>
      (super.noSuchMethod(
            Invocation.method(#formatEventTime, [event]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#formatEventTime, [event]),
            ),
          )
          as String);

  @override
  String getBuildingAbbreviation(String? location) =>
      (super.noSuchMethod(
            Invocation.method(#getBuildingAbbreviation, [location]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#getBuildingAbbreviation, [location]),
            ),
          )
          as String);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
