appId: com.example.concordia_nav
---
- tapOn: "ConU Nav"
- assertVisible: "Concordia Campus Guide"
- tapOn:
    point: "7%,9%"
- assertVisible: "Settings"
- assertVisible: "Preferences"
- tapOn: "Preferences"
