name: Run Integration Tests
description: All Integration Tests in the maestro folder will be run.
inputs:
  is-main:
    description: "Is this the main branch?"
    required: true
    default: "false"
runs:
  using: "composite"
  steps:        
    - name: Install Maestro CLI
      shell: bash
      run: |
        curl -Ls https://get.maestro.mobile.dev | bash
        echo "$HOME/.maestro/bin" >> $GITHUB_PATH
      
    - name: AVD Cache
      uses: actions/cache@v4
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: ${{ runner.os }}-avd-35

    - name: Create AVD and Generate Snapshot for Caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 35
        target: default
        arch: x86_64
        force-avd-creation: false
        emulator-options: -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: echo "Generated AVD snapshot for caching."

    - name: Set Script Variable
      shell: bash
      id: set-script
      run: |
        if [ "${{ inputs.is-main }}" == "true" ]; then
          echo "script=rps install && rps test record" >> $GITHUB_ENV
        else
          echo "script=rps install && rps test integration" >> $GITHUB_ENV

    # - name: Install libpulse Dependency
    #   shell: bash
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y libpulse0

    - name: Run Integration Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 35
        target: default
        arch: x86_64
        force-avd-creation: false
        emulator-options: -noaudio -no-boot-anim -camera-back none -gpu swiftshader_indirect
        disable-animations: ${{ inputs.is-main == 'true' && 'true' || 'false' }}
        script: ${{ env.script }}
