// Mocks generated by Mockito 5.4.5 from annotations
// in concordia_nav/test/map/campus_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:concordia_nav/data/domain-model/concordia_campus.dart' as _i5;
import 'package:concordia_nav/data/repositories/map_repository.dart' as _i7;
import 'package:concordia_nav/data/services/map_service.dart' as _i8;
import 'package:concordia_nav/data/domain-model/concordia_building.dart' as _i9;
import 'package:concordia_nav/utils/map_viewmodel.dart' as _i3;
import 'package:flutter/material.dart' as _i6;
import 'package:google_maps_flutter/google_maps_flutter.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCameraPosition_0 extends _i1.SmartFake
    implements _i2.CameraPosition {
  _FakeCameraPosition_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [ValueNotifier].
class MockValueNotifier<T> extends _i1.Mock implements _i6.ValueNotifier<T> {}

/// A class which mocks [MapViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockMapViewModel extends _i1.Mock implements _i3.MapViewModel {
  MockMapViewModel() {
    _i1.throwOnMissingStub(this);
  }

    @override
  _i6.ValueNotifier<_i9.ConcordiaBuilding?> get selectedBuildingNotifier => MockValueNotifier();

  @override
  _i4.Future<_i2.CameraPosition> getInitialCameraPosition(
    _i5.ConcordiaCampus? campus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#getInitialCameraPosition, [campus]),
        returnValue: _i4.Future<_i2.CameraPosition>.value(
          _FakeCameraPosition_0(
            this,
            Invocation.method(#getInitialCameraPosition, [campus]),
          ),
        ),
      ) as _i4.Future<_i2.CameraPosition>);

  @override
  void onMapCreated(_i2.GoogleMapController? controller) => super.noSuchMethod(
        Invocation.method(#onMapCreated, [controller]),
        returnValueForMissingStub: null,
      );

  @override
  void moveToLocation(_i2.LatLng? location) => super.noSuchMethod(
        Invocation.method(#moveToLocation, [location]),
        returnValueForMissingStub: null,
      );

  @override
  void switchCampus(_i5.ConcordiaCampus? campus) => super.noSuchMethod(
        Invocation.method(#switchCampus, [campus]),
        returnValueForMissingStub: null,
      );

  @override
  void selectBuilding(_i9.ConcordiaBuilding? building) => super.noSuchMethod(
        Invocation.method(#selectBuilding, [building]),
        returnValueForMissingStub: null,
      );

  @override
  void unselectBuilding() => super.noSuchMethod(
        Invocation.method(#unselectBuilding, []),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<Map<String, dynamic>> getCampusPolygonsAndLabels(
    _i5.ConcordiaCampus? campus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#getCampusPolygonsAndLabels, [campus]),
        returnValue: _i4.Future<Map<String, dynamic>>.value(
          <String, dynamic>{},
        ),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.LatLng?> fetchCurrentLocation() => (super.noSuchMethod(
        Invocation.method(#fetchCurrentLocation, []),
        returnValue: _i4.Future<_i2.LatLng?>.value(),
      ) as _i4.Future<_i2.LatLng?>);

  @override
  _i4.Future<bool> checkLocationAccess() => (super.noSuchMethod(
        Invocation.method(#checkLocationAccess, []),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> moveToCurrentLocation(_i6.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(#moveToCurrentLocation, [context]),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> zoomIn() => (super.noSuchMethod(
        Invocation.method(#zoomIn, []),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> zoomOut() => (super.noSuchMethod(
        Invocation.method(#zoomOut, []),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [MapRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMapRepository extends _i1.Mock implements _i7.MapRepository {
  MockMapRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CameraPosition getCameraPosition(_i5.ConcordiaCampus? campus) =>
      (super.noSuchMethod(
        Invocation.method(#getCameraPosition, [campus]),
        returnValue: _FakeCameraPosition_0(
          this,
          Invocation.method(#getCameraPosition, [campus]),
        ),
      ) as _i2.CameraPosition);
}

/// A class which mocks [MapService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMapService extends _i1.Mock implements _i8.MapService {
  MockMapService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setMapController(_i2.GoogleMapController? controller) =>
      super.noSuchMethod(
        Invocation.method(#setMapController, [controller]),
        returnValueForMissingStub: null,
      );

  @override
  _i2.CameraPosition getInitialCameraPosition(_i5.ConcordiaCampus? campus) =>
      (super.noSuchMethod(
        Invocation.method(#getInitialCameraPosition, [campus]),
        returnValue: _FakeCameraPosition_0(
          this,
          Invocation.method(#getInitialCameraPosition, [campus]),
        ),
      ) as _i2.CameraPosition);

  @override
  void moveCamera(_i2.LatLng? position, {double? zoom = 17.0}) =>
      super.noSuchMethod(
        Invocation.method(#moveCamera, [position], {#zoom: zoom}),
        returnValueForMissingStub: null,
      );

  _i4.Future<Map<String, dynamic>> getCampusPolygonsAndLabels(
    _i5.ConcordiaCampus? campus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#getCampusPolygonsAndLabels, [campus]),
        returnValue: _i4.Future<Map<String, dynamic>>.value(
          <String, dynamic>{},
        ),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> zoomIn() => (super.noSuchMethod(
        Invocation.method(#zoomIn, []),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> zoomOut() => (super.noSuchMethod(
        Invocation.method(#zoomOut, []),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isLocationServiceEnabled() => (super.noSuchMethod(
        Invocation.method(#isLocationServiceEnabled, []),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> checkAndRequestLocationPermission() => (super.noSuchMethod(
        Invocation.method(#checkAndRequestLocationPermission, []),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.LatLng?> getCurrentLocation() => (super.noSuchMethod(
        Invocation.method(#getCurrentLocation, []),
        returnValue: _i4.Future<_i2.LatLng?>.value(),
      ) as _i4.Future<_i2.LatLng?>);
}
