name: Setup Android Build
description: Sets up the Android build environment
inputs:
  sdk-version:
    description: 'SDK Version to Install (Long version, e.g. 12266719)'
    required: true
    default: '12266719'
runs:
  using: composite
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: 'gradle'
        cache-dependency-path: |
          ./concordia_nav/android/*.gradle*
          ./concordia_nav/android/**/gradle-wrapper.properties
          android/build.gradle
          android/app/build.gradle
          android/gradle/wrapper/gradle-wrapper.properties

    - name: Restore Android SDK Cache
      uses: actions/cache@v3
      id: cache-sdk
      with:
        path: ${{ runner.tool_cache }}/android-sdk
        key: ${{ runner.os }}-android-sdk-${{ inputs.sdk-version }}

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: ${{ inputs.sdk-version }}
        accept-android-sdk-licenses: true
        log-accepted-android-sdk-licenses: false

    - name: Save Android SDK Cache
      if: steps.cache-sdk.outputs.cache-hit != 'true'
      uses: actions/cache@v3
      with:
        path: ${{ runner.tool_cache }}/android-sdk
        key: ${{ runner.os }}-android-sdk-${{ inputs.sdk-version }}