name: Setup Flutter
description: Runs the Flutter setup action and installs dependencies
runs:
  using: composite
  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      id: flutter-action
      with:
        channel: stable
        cache: true
    - shell: bash
      run: flutter --version

    - name: Install dependencies
      shell: bash
      working-directory: ./concordia_nav
      run: flutter pub get

    - name: Install rps package globally
      shell: bash
      run: dart pub global activate rps