name: Build Android 
description: Builds the Android .apk in release or debug mode depending on the branch refs.
inputs:
  release:
    description: 'Whether to build in release mode'
    required: true
    default: 'false'
  keystore-base64:
    description: 'Keystore Base64 Encoded'
    required: true
  keystore-password:
    description: 'Keystore Password'
    required: true
  key-password:
    description: 'Key Password'
    required: true
  key-alias:
    description: 'Key Alias'
    required: true
runs:
  using: composite
  steps:
  - name: Build Type
    shell: bash
    run: |
      if [ "${{ inputs.release }}" == 'true' ]; then
        echo "[INFO] Building in release mode."
      elif [ "${{ inputs.release }}" == 'false' ]; then
        echo "[INFO] Building in debug mode."
      else
        echo "[ERROR] Invalid parameter for 'release'. Expected 'true' or 'false' got '${{ inputs.release }}'."
        exit 1
      fi
  
  - name: Decode Keystore
    if: ${{ inputs.release == 'true' }}
    working-directory: ./concordia_nav
    shell: bash
    run: |
      base64 -d <<< "${{ inputs.keystore-base64 }}" > android/app/upload-keystore.jks

  - name: Configure Gradle Properties
    if: ${{ inputs.release == 'true' }}
    working-directory: ./concordia_nav
    shell: bash
    run: |
      {
        echo "storePassword=${{ inputs.keystore-password }}"
        echo "keyPassword=${{ inputs.key-password }}"
        echo "keyAlias=${{ inputs.key-alias }}"
        echo "storeFile=upload-keystore.jks"
      } > android/key.properties

  - name: Build APK
    working-directory: ./concordia_nav
    shell: bash
    run: |
      if [ "${{ inputs.release }}" == 'true' ]; then
        rps build android --release
      else
        rps build android --debug
      fi