name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/shared-setup.yaml
    secrets: inherit

  test:
    name: 🧪 Run Tests
    needs: [setup]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./concordia_nav
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Download .env file
      uses: actions/download-artifact@v4
      with:
        name: env-file

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        accept-android-licenses: true

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      id: flutter-action
      with:
        channel: stable
        cache: true
    - run: flutter --version

    - name: Install dependencies
      run: flutter pub get

    - name: Install rps package globally
      run: dart pub global activate rps

    - name: Run linter
      run: rps lint check
    
    - name: Run unit tests
      run: rps test unit

    - name: Build (Debug)
      run: rps build android --debug
    
    # - name: Enable KVM group perms
    #   if: ${{ runner.os == 'Linux' }}
    #   run: |
    #     if [ -e /dev/kvm ]; then
    #       sudo sh -c 'echo "KERNEL==\"kvm\", GROUP=\"kvm\", MODE=\"0666\", OPTIONS+=\"static_node=kvm\"" > /etc/udev/rules.d/99-kvm4all.rules'
    #       sudo udevadm control --reload-rules
    #       sudo udevadm trigger --name-match=kvm
    #     else
    #       echo "Skipping KVM setup as /dev/kvm is not available."
    #     fi

    # - name: Run Integration Tests
    #   uses: reactivecircus/android-emulator-runner@v2
    #   with:
    #     api-level: 35
    #     script: rps test integration

  coverage:
    name: 📊 Coverage
    needs: [setup]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./concordia_nav
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download .env file
      uses: actions/download-artifact@v4
      with:
        name: env-file

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      id: flutter-action
      with:
        channel: stable
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Install rps package globally
      run: dart pub global activate rps

    - name: Generate Code Coverage Report
      run: rps coverage

    - name: Upload Coverage Report to Codecov
      uses: codecov/codecov-action@v5
      with:
        directory: ./concordia_nav/coverage
        fail_ci_if_error: false
        files: ./lcov.info,
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: NathanGrenier/SOEN-390

  sonarqube:
    name: 🔍 SonarQube
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./concordia_nav
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v4
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}